### PR TITLE
Added year as an option to movie search

### PR DESCRIPTION
**Pull request by mskog**
I have added "year" as a possible option when searching for movies as described in 
http://help.themoviedb.org/kb/api/search-movies

I am using this in my own movie identification gem to tell the difference between "Total Recall" and the 2012 remake for example

### CODE REVIEW

**Comment by Irio** [comment]
@MrCheese Can you fix the conflicts so I can merge it? Next I'll be working on some refactoring on TmdbMovie.find to make it more simple and remove this bunch of if's.

**Comment by luxflux** [comment]
What's up here? Will you merge?

**Comment by Irio** [comment]
Sure, sorry.

**Comment by luxflux** [comment]
Cool! Thanks a lot.

**Pull request merged**
