### PR TITLE
Added trailer informations to api extended results

### PR DESCRIPTION
**Pull request by Flink**
I think it’s pretty much self-describing :)

### CODE REVIEW

**Comment by Irio** [comment]
Past week I was discussing about the need of trailers in a project, so you speed up the implementation. Thanks!

I just created a Gemfile of the project ( https://github.com/Irio/ruby-tmdb/commits/master/Gemfile ). Can you remove it from your `.gitignore`'s path?

And would be pretty awesome if you could add tests, like `test_fetch_trailers_with_expansion_enabled`.

**Comment by Flink** [comment]
Done :)

**Comment by Irio** [comment]
What about a test for fail scenario? "find without expanison enabled should not return trailers"

**Comment by Flink** [comment]
Ok, done too ;)

**Pull request merged**
